default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: "*"
      threads: 3
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 0.1

development:
  dispatchers:
    - polling_interval: 1
      batch_size: 500
      concurrency_maintenance_interval: 300
  workers:
    - queues: "*"
      threads: 3
      processes: 1
      polling_interval: 2
    - queues: [real_time, background]
      threads: 5
      processes: 1
      polling_interval: 0.1
      processes: 3

test:
  dispatchers:
    - polling_interval: 1
      batch_size: 500
      concurrency_maintenance_interval: 300
  workers:
    - queues: "*"
      threads: 3
      processes: 1
      polling_interval: 2
    - queues: [real_time, background]
      threads: 5
      processes: 1
      polling_interval: 0.1
      processes: 3

production:
  <<: *default
